### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by Aplex2723** [hoangducdt/MojiaGarages#104]
![image](https://user-images.githubusercontent.com/72839304/160940573-bb7c801d-d8f9-4db1-bb02-2eb8e9058719.png)

I get this error in a loop, unfortunately I don't know what to do and I can't find the error, implement everything necessary within the radialmenu script.

**Comment by RicanPlayaTTv** [comment]
I noticed that the newest qb-radialmenu has a dynamic vehicle menu that hides when you are not in a vehicle.
So addSubMenu can't do anything if the menu is not there. I had to revert to and older qb-radialmenu for it to work.
