### ISSUE TITLE
Error creating new garage

### ISSUE THREAD

**Issue by justBMR** [hoangducdt/MojiaGarages#106]
When I try to create a new garage, I make an exact copy of the code of one of the garages, I change the name of the garage (from 'garage7' to 'garage8'), I indicate the polyzon coordinates and the vehicles' spawn points. When I restart the script, it gives qb-core error. Any idea what I could be doing an error?
![erro](https://user-images.githubusercontent.com/93486510/161396018-f480e4fa-ae5a-4862-84a8-fe7213252c83.png)

The code below, is my code copied and already programmed for the garage. It is placed in config.lua between lines 499 (after the }, of the garage7 code) and line 555 (before the ['depot'] = { )

['garage8'] = {
        label = 'Garagem do motel',
        spawnPoint = {
			vector4(293.67, -349.98, 44.53, 69.77),
			vector4(293.95, -346.15, 44.51, 69.56),
			vector4(295.32, -343.13, 44.51, 70.17),
			vector4(296.3, -339.63, 44.51, 69.48),
			vector4(297.65, -336.4, 44.51, 69.45),
			vector4(298.64, -333.12, 44.51, 69.02),
			vector4(300.23, -330.02, 44.51, 70.8),
			vector4(289.96, -326.42, 44.51, 249.04),
			vector4(271.26, -319.42, 44.51, 249.97),
			vector4(270.05, -322.64, 44.51, 250.53),
			vector4(287.91, -329.2, 44.51, 249.79),
			vector4(286.86, -332.59, 44.51, 248.77),
			vector4(268.85, -325.83, 44.51, 248.9),
			vector4(267.61, -329.14, 44.51, 250.08),
			vector4(285.63, -335.72, 44.51, 249.1),
			vector4(284.98, -339.26, 44.51, 249.79),
			vector4(266.59, -332.37, 44.51, 250.97),
			vector4(283.03, -342.21, 44.51, 248.94),
			vector4(277.24, -340.15, 44.51, 71.75),
			vector4(278.2, -336.57, 44.51, 70.05),
			vector4(279.38, -333.37, 44.51, 68.98),
			vector4(280.43, -330.16, 44.51, 69.08),
			vector4(281.65, -326.98, 44.51, 70.01),
			vector4(282.77, -323.75, 44.51, 70.03),
		},
		blippoint = vector3(275.12, -345.5, 45.17),
        showBlip = true,
		blipsprite = 357,
		blipscale = 0.65,
		blipcolour = 3,
		job = nil, -- [nil: public garage] ['police: police garage'] ...
		fullfix = true, -- [true: full fix when take out vehicle]
		garastate = 1, -- [0: Depot] [1: Garage] [2: Impound]
		isHouseGarage = false,
		canStoreVehicle = true,
		zones = {
			vector2(295.06, -354.5),  --45.36)
			vector2(287.96, -352.18), --45.3)
			vector2(286.0, -356.33),  --45.34)
			vector2(280.14, -353.97), --45.22)
			vector2(281.67, -349.88), --45.17)
			vector2(273.68, -346.57), --44.92)
			vector2(271.9, -350.94),  --45.21)
			vector2(265.44, -348.65), --45.16)
			vector2(267.14, -344.25), --45.12)
			vector2(265.79, -343.36), --45.12)
			vector2(267.88, -337.59), --45.02)
			vector2(260.91, -334.99), --45.02)
			vector2(267.76, -315.97), --45.02)
			vector2(304.54, -329.18), --45.02)
        },
  		minZ = 44.671352386475 - 1,
  		maxZ = 46.789905548096 + 1
    },

**Comment by zh-development** [comment]
you need to change the zones with vector2 to this no you forgot to add    ,


vector2(295.06, -354.5), --45.36),
vector2(287.96, -352.18), --45.3),
vector2(286.0, -356.33), --45.34),
vector2(280.14, -353.97), --45.22),
vector2(281.67, -349.88), --45.17),
vector2(273.68, -346.57), --44.92),
vector2(271.9, -350.94), --45.21),
vector2(265.44, -348.65), --45.16),
vector2(267.14, -344.25), --45.12),
vector2(265.79, -343.36), --45.12),
vector2(267.88, -337.59), --45.02),
vector2(260.91, -334.99), --45.02),
vector2(267.76, -315.97), --45.02),
vector2(304.54, -329.18), --45.02),
