### ISSUE TITLE
Car dupe persists

### ISSUE THREAD

**Issue by Baelroak** [hoangducdt/MojiaGarages#107]
With todays update just driving around even with real parking config set to false a trail of duped cars occurs almost like a snake 
Using onesync infinity

![image](https://user-images.githubusercontent.com/68571188/161496277-557a4171-5a66-4e4a-9b90-53718faf9197.png)

**Comment by geekgfx** [comment]
same need a fix for this

**Comment by zh-development** [comment]
is this still a problem with the new version

**Comment by Baelroak** [comment]
> is this still a problem with the new version

yes, the older version I could disable real parking with config, now even with real parking set to false it happens

**Comment by daddyDUBZ** [comment]
Car duplication persists

**Comment by daddyDUBZ** [comment]
https://i.imgur.com/I6NhLXR.jpeg
