### ISSUE TITLE
Script is broken will be watching for a working update before implemening.

### ISSUE THREAD

**Issue by geekgfx** [hoangducdt/MojiaGarages#109]
In its current state this script is currently broken, the vehicles spawn behind you in a trail even with the real parking disabled i also keep getting errors with failed to perform arithmetic on nil value 'bodyhealth'

**Comment by zh-development** [comment]
the nil value body health is becuas you got a bodyhealt in you database there is bigger then 1000 or small then 0

**Comment by geekgfx** [comment]
> the nil value body health is becuas you got a bodyhealt in you database there is bigger then 1000 or small then 0

Thanks will look at this when I get home
