### ISSUE TITLE
Error in new qb-radialmenu

### ISSUE THREAD

**Issue by Duruteu** [hoangducdt/MojiaGarages#110]
Hello, this error is appearing for me in the new qb-radialmenu, how to solve it
![20220405183717_1](https://user-images.githubusercontent.com/31866110/161854018-02e9960c-f63e-437c-b1b3-b131a4be853b.jpg)
?

**Comment by mikeyxb** [comment]
what was the resolution for this please?

**Comment by mikeyxb** [comment]
@Duruteu could you let me know how you resolved that issue please I am having the same

**Comment by Duruteu** [comment]
It's just you put
local garaIndex = nil
local function SetupGaragesMenu()
    local isingarage, canStoreVehicle = exports["MojiaGarages"]:IsInGarage()
	local GaragesMenu = {
        id = 'garages',
        title = 'Garages',
        icon = 'warehouse',
        items = {}
    }
	if isingarage then
		GaragesMenu.items[#GaragesMenu.items+1] = {
			id = 'opengarage',
			title = 'Open Garage',
			icon = 'warehouse',
			type = 'client',
			event = 'MojiaGarages:client:openGarage',
			shouldClose = false,
		}
		local veh = nil
		local ped = PlayerPedId()
		local pos = GetEntityCoords(ped)
		local vehout, distance = QBCore.Functions.GetClosestVehicle(pos)
		local vehin = IsPedInAnyVehicle(ped, true)
		if vehin then
			veh = GetVehiclePedIsIn(ped)
		else
			if NetworkGetEntityIsLocal(vehout) and distance <= 5 then
				veh = vehout
			end
		end
		if veh ~= nil then
			local plate = QBCore.Functions.GetPlate(veh)
			if exports["qb-vehiclekeys"]:HasVehicleKey(plate) then
				if canStoreVehicle then
					GaragesMenu.items[#GaragesMenu.items+1] = {
						id = 'storeVehicle',
						title = 'Store Vehicle',
						icon = 'parking',
						type = 'client',
						event = 'MojiaGarages:client:storeVehicle',
						shouldClose = false,
					}
				end
			end
		end
	end
    if #GaragesMenu.items == 0 then
        if garaIndex then
            RemoveOption(garaIndex)
            garaIndex = nil
        end
    else
        garaIndex = AddOption(GaragesMenu, garaIndex)
    end
end

Before the 

local function SetupSubItems()
    SetupJobMenu()
    SetupVehicleMenu()
	SetupGaragesMenu()
end
