### ISSUE TITLE
Error in qb-radialmenu

### ISSUE THREAD

**Issue by MrRasmus** [hoangducdt/MojiaGarages#115]
Issues with qb-radialmenu after installing script - I followed the Readme 100% - 2 Attempts and still these errors
![mojijagarageserror](https://user-images.githubusercontent.com/43639948/162913628-b73a1449-ef42-499a-b803-5891e94b1cef.png)

**Comment by hoangducdt** [comment]
Please use the latest update, addSubMenu has been deprecated

**Comment by MrRasmus** [comment]
I have used the latest update

tir. 12. apr. 2022 kl. 11.16 skrev Hoàng Đức ***@***.***>:

**Comment by MrRasmus** [comment]
Okay so Solved the addsubmenu - It was just written in the changelog - My mistake
I now did the things in the readme - But get a Error around No such export CheckHasKey in resource MojiaVehicleKeys
![image](https://user-images.githubusercontent.com/43639948/162971334-d0af194c-2b21-4561-9b55-7d73f1397b05.png)

**Comment by MrRasmus** [comment]
Im using qb-vehiclekeys - Code is like this
`				if exports["qb-vehiclekeys"]:HasVehicleKey(plate) then --disable if use MojiaVehicleKeys
			--if exports['MojiaVehicleKeys']:CheckHasKey(plate) then --enable if use MojiaVehicleKeys`

**Comment by MrRasmus** [comment]
Solved after carefully following the readme 

Still has problems with unable to obtain keys for vehicle after restart

**Comment by twigmasters** [comment]
I am having this same issue
![image](https://user-images.githubusercontent.com/64451461/163525064-96cbfb9e-0089-4634-8a00-a60c6e6af1b2.png)
How did you fix it?

**Comment by MrRasmus** [comment]
In your mojiagarage config file, set using mojiakeys to false

fre. 15. apr. 2022 kl. 07.28 skrev twigmasters ***@***.***>:

**Comment by twigmasters** [comment]
Problem is I am trying to use mojiakeys and if gives me the error when I enable that setting in mojiagarage
