### ISSUE TITLE
qb-vehiclekeys refactor - changed events and functions

### ISSUE THREAD

**Issue by MrRasmus** [hoangducdt/MojiaGarages#118]
The new update for vehicle keys changed alot of names on functions etc. I don't know how to make a pull request on it. 
Of course it will be sometimes you have time for it, you do an amazing job and I like your script

**Comment by daddyDUBZ** [comment]
Think we just need to change the export in Mojia to match the new vehicle keys. gonna give it a shot

**Comment by Darkkang94** [comment]
Hi, are there anything new? I need fix the qb-vehiclekeys for MojiaGarages, thanks

**Comment by daddyDUBZ** [comment]
if exports['qb-vehiclekeys']:HasKeys(plate) then
				
				Need to change HasVehicleKey to what you see above in the Mojia client.lua

**Comment by daddyDUBZ** [comment]
-- local function HasVehicleKey(plate)
-- 	QBCore.Functions.TriggerCallback('vehiclekeys:server:CheckHasKey', function(result)
-- 		if result then
-- 			HasVehicleKey = true
-- 		else
-- 			HasVehicleKey = false
-- 		end
-- 	end, plate)
-- 	return HasVehicleKey
-- end
-- exports('HasVehicleKey', HasVehicleKey)

this is also no longer needed in qb-vehiclekeys in this refactor

**Comment by Darkkang94** [comment]
Hi. I changed all as you said, but i've this error: No such export HasKeys in resourc qb-vehiclekeys. I changed all the exports to exports['qb-vehiclekeys']:HasKeys(plate) in qb-radialmenu and MojiaGarages and i've the qb-vehiclekey updated.

Thanks.
