### ISSUE TITLE
'RealParking' fails after server restart.

### ISSUE THREAD

**Issue by gitSNAKEgit** [hoangducdt/MojiaGarages#124]
'RealParking' works fine until the server restarts, then it's not possible to unlock the car as the user doesn't have keys to the car.

**Comment by mikeyxb** [comment]
i can confirm i have this issue also

**Comment by Maverick167** [comment]
Why was this closed? It's still happening.

**Comment by JustMeGaming** [comment]
The fix is located here.

https://github.com/hoangducdt/MojiaGarages/issues/133#issuecomment-1143161271
