### ISSUE TITLE
All garages joined/public?

### ISSUE THREAD

**Issue by Purenoiz** [hoangducdt/MojiaGarages#125]
Is there anyway to put a vehicle in one garage and take it out at another garage? Thanks

**Comment by hoangducdt** [comment]
It's an absurd thing, so we definitely won't do it

**Comment by Purenoiz** [comment]
Umm. Absurd? I thought it was pretty common. Alot of the servers I've played have a shared garage system.

**Comment by hoangducdt** [comment]
It is only true for a non-RP server.
