### ISSUE TITLE
[ đề xuất ]

### ISSUE THREAD

**Issue by xenfovn** [hoangducdt/MojiaGarages#13]
1 - thêm tính năng access citizenid giống job 
2 - làm thêm house garages

**Comment by xenfovn** [comment]
cái 1 tức là thêm config ví dụ citizenid = "ABC123" thì mới có quyền truy cập garage , có tác dụng thay thế gara nhà chỉ 1 chủ sở hữu

**Comment by hoangducdt** [comment]
house gara thì tôi đang xem code cuar qb-house để thêm sao cho hợp lý, vì cái đó là nhà được môi giới tạo, tọa độ cũng do họ set mà thời gian rảnh tôi hơi ít nên sẽ hơi lâu một chút, còn cái 1 thấy nó không hợp lý, nếu có house garage với public garage mà còn thêm cái này là nó bất hợp lý
