### ISSUE TITLE
[REQUEST] Gang option for garages

### ISSUE THREAD

**Issue by TrueSunnyD** [hoangducdt/MojiaGarages#15]
Are you able to add gang specific garages? Giving us the choice to be able to do either jobs or gangs? 

Amazing script by the way!

**Comment by hoangducdt** [comment]
![image](https://user-images.githubusercontent.com/32219904/146877622-e7e09bbc-a567-4427-ade0-f98132b93855.png)
it's already in the script

**Comment by xenfovn** [comment]
@hoangducdt gang là job 2 ông ơi , để chiều tối tôi nghiên cứu rồi pr cho

**Comment by hoangducdt** [comment]
gang là băng đảng chứ?

**Comment by hoangducdt** [comment]
à nó không nằm trong job đúng ko? này cũng chưa test gang =))

**Comment by hoangducdt** [comment]
CreateThread(function() 
    for k, v in pairs(Garages) do
		Stations[k] = PolyZone:Create(v.zones, {
			name="GarageStation "..k,
			minZ = 	v.minz,
			maxZ = v.maxz,
			debugPoly = true
		})
		Stations[k]:onPlayerInOut(function(isPointInside)
			if isPointInside then
				if Garages[k].job ~= nil then
					PlayerData = QBCore.Functions.GetPlayerData()
					if PlayerData.job.name == Garages[k].job or PlayerData.gang == Garages[k].job then
						inGarageStation = true
						currentgarage = k
					else
						inGarageStation = false
						currentgarage = nil
					end
				else
					inGarageStation = true
					currentgarage = k
				end
			else
				inGarageStation = false
				currentgarage = nil
			end
		end)
    end
end)
tôi đang ở chỗ làm, ông test dùm tôi thử
