### ISSUE TITLE
no spawn

### ISSUE THREAD

**Issue by Dvk1211** [hoangducdt/MojiaGarages#16]
Car garages great but doesnt spawn when I try. Makes the little noise like something is stopping it. No errors, correct trigger. Has anyone seen?

**Comment by xenfovn** [comment]
make sure u using qbcore latest version

**Comment by idrp** [comment]
![image](https://user-images.githubusercontent.com/88186466/147097661-1eda284b-e013-4c80-9bc4-b85bb3076c39.png)

Was working fine, did updates today now getting this error.  Any Ideas?

**Comment by idrp** [comment]
![image](https://user-images.githubusercontent.com/88186466/147113685-fdfa6e08-ee20-4bed-ace4-40ccbbdac343.png)

**Comment by idrp** [comment]
Ah needed to add  local to PlayerData = QBCore.Functions.GetPlayerData()  blips now showing

**Comment by hoangducdt** [comment]
> ![image](https://user-images.githubusercontent.com/88186466/147097661-1eda284b-e013-4c80-9bc4-b85bb3076c39.png)
> 
> Was working fine, did updates today now getting this error. Any Ideas?

![image](https://user-images.githubusercontent.com/32219904/147115103-dce12b6b-2ba2-4378-b219-b84364a8d94f.png)
my fault, fixed

**Comment by hoangducdt** [comment]
![image](https://user-images.githubusercontent.com/32219904/147115584-7dd6c680-0631-4b6a-9fe0-49494fc97b84.png)
