### ISSUE TITLE
[Question] Hello

### ISSUE THREAD

**Issue by ImpulseFPS** [hoangducdt/MojiaGarages#18]
So my question is:
Is the garage now fully set up with houses because that was the only thing holding me back from using it. thanks in advance

**Comment by hoangducdt** [comment]
Yes! however you need to delete the entire garage of the houses previously created on sql and recreate. when creating a new garage you need to sit in a car! You can see the full functionality here: https://youtu.be/1ECZIyZEmhY

**Comment by ImpulseFPS** [comment]
All Aight thanks for the amazing work, btw the radial menu is default QB, or is it raid?, one more question tho could you in a feature update make that players can share the garage. pure example is NoPixel garage system where player can give another player access to there garage vehicles, and maybe something like for scratched vehicles same shit nopixel example

**Comment by BlueSky-fur** [comment]
i second Impulse's idea, would be cool to be able to share garages!

**Comment by hoangducdt** [comment]
> All Aight thanks for the amazing work, btw the radial menu is default QB, or is it raid?, one more question tho could you in a feature update make that players can share the garage. pure example is NoPixel garage system where player can give another player access to there garage vehicles, and maybe something like for scratched vehicles same shit nopixel example

Great idea, I'll try that in my free time, but this probably requires sql,

**Comment by ImpulseFPS** [comment]
About the radial menu defualt qb or raid?

**Comment by hoangducdt** [comment]
> About the radial menu defualt qb or raid?

This menu is my own, based on many sources, you can find it on my github
