### ISSUE TITLE
[Issue] bad argument for vector4

### ISSUE THREAD

**Issue by BlueSky-fur** [hoangducdt/MojiaGarages#19]
i just installed the script with your guide and all, but noticed when starting the server it gives an error for a vector4 coordinate

`[ script:MojiaGarages] SCRIPT ERROR: @MojiaGarages/server.lua:46: bad argument #1 to 'vector4' (invalid vector type)
[ script:MojiaGarages] > handler (@MojiaGarages/server.lua:46)
[ script:MojiaGarages] > safeCallback (@oxmysql/oxmysql.js:20087)
[ script:MojiaGarages] > <unknown> (@oxmysql/oxmysql.js:20094)
[ script:MojiaGarages] > processTicksAndRejections (node:internal/process/task_queues:96)`

**Comment by BlueSky-fur** [comment]
it also spits out an error for our MDT now as it seems to search for something that doesnt exist

**Comment by BlueSky-fur** [comment]
Ill put it here too, i also cant seem to get your radialmenu events working.

i added them like this

`Config.MenuItems =  {
    {
        id = "policeDeadA",
        displayName = "10-13A",
        icon = "#police-dead",
        functionName = "police:client:SendPoliceEmergencyAlert",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return (Data.metadata["isdead"] or Data.metadata["inlaststand"]) and Data.job.name == 'police'
        end
    },
    {
        id = "emsDeadA",
        displayName = "10-14A",
        icon = "#ems-dead",
        functionName = "police:client:SendPoliceEmergencyAlert",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return (Data.metadata["isdead"] or Data.metadata["inlaststand"]) and Data.job.name == 'ambulance' or Data.job.name == 'ems'
        end
    },
    {
        id = "general",
        displayName = "General",
        icon = "#globe-europe",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return not Data.metadata["isdead"] and not Data.metadata["inlaststand"]
        end,
        subMenus = {"vehicle:giveKeys", "general:flipveh", "general:hotdog", "general:givenum", "general:getintrunk"}
    },
    {
        id = "cornersell",
        displayName = "Cornersell",
        icon = "#cornersell",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return not Data.metadata["isdead"] and not Data.metadata["inlaststand"]
        end,
        subMenus = {"cornersell:cocaine",}
    },

     {
         id = "house",
         displayName = "House Interaction",
         icon = "#house",
         enableMenu = function()
             local Data = QBCore.Functions.GetPlayerData()
             return not Data.metadata["isdead"] and not Data.metadata["inlaststand"]
         end,
         subMenus = {"house:give","house:remove", "house:doorlock", "house:reset", "house:decorate", "house:setstash", "house:setoutift", "house:setlogout"}
     },

    {
        id = "tow",
        displayName = "Tow Actions",
        icon = "#mechanic",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and (Data.job.name == "tow"))
        end,
        subMenus = {"tow:togglenpc","tow:towvehicle"}
    },

    {
        id = "cuff",
        displayName = "Interaction",
        icon = "#cuffs",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return not Data.metadata["isdead"] and not Data.metadata["inlaststand"]
        end,
        subMenus = { "cuffing:cuff", "cuffing:steal", 'ems:putinvehicle','ems:unseatvehicle', 'police:carry', 'police:drag', 'police:takehostage'}
    },
       

    {
        id = "vehicle",
        displayName = "Vehicle",
        icon = "#vehicle-options",
        functionName = "vehcontrol:openExternal",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and IsPedInAnyVehicle(PlayerPedId(), false))
        end
    },

    {
        id = "strippers",
        displayName = "Stripper Bitches",
        icon = "#stripper-bitches",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and (Data.job.name == "unicorn"))
        end,
        subMenus = { "deadblip:sendBlip"}
    },

    {
        id = "mechanic",
        displayName = "Mechanic Actions",
        icon = "#mechanic",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "mechanic")
        end,
        subMenus = { "mechanic:impound", "mechanic:flatbed" }
    },

    {
        id = "judge",
        displayName = "Judge Actions",
        icon = "judge-actions",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "mayor" and Data.job.grade >= 2)
        end,
        subMenus = { 'judge:mdt' }
    },

    {
        id = "mechanicbus",
        displayName = "Mechanic",
        icon = "#mechanic",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "mechanicbus")
        end,
        subMenus = { "mechanicbus:bill","mechanic:lookupvehicle", "mechanic:wash", "mechanic:impound", "mechanic:flatbed" }
    },

    {
        id = "suflakius",
        displayName = "Mechanic",
        icon = "#mechanic",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "suflakius")
        end,
        subMenus = { "suflakius:bill","mechanic:lookupvehicle", "mechanic:wash", "mechanic:impound", "mechanic:flatbed" }
    },

    {
        id = "taxi",
        displayName = "Taxi",
        icon = "#taxi",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "taxi")
        end,
        subMenus = { "taxi:togglemeter", "taxi:npcmission", "taxi:togglefare" }
    },

    {
        id = "police",
        displayName = "Police",
        icon = "#police",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "police")
        end,
        subMenus = {"police:drag", "police:search", "police:mdt", "police:softcuff", "police:cuff", "ems:putinvehicle","ems:unseatvehicle", "police:duty", "ems:status", "police:status"}
    },

    {
        id = "vehicleextras",
        displayName = "Vehicle Extras",
        icon = "#police",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and IsPedInAnyVehicle(PlayerPedId(), false) and Data.job ~= nil and Data.job.name == "police" or Data.job.name == "ambulance" or Data.job.name == "ems")
        end,
        subMenus = {"extra1", "extra2", "extra3", "extra4", "extra5", "extra6", "extra7", "extra8", "extra9",}
    },

    {
        id = "objects",
        displayName = "Objetcs",
        icon = "#objects",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "ambulance" or Data.job.name == "police")
        end,
        subMenus = {"objects:barier", "objects:cone", "objects:tent", "objects:spike", "objects:board", "objects:light", "objects:remove"}
    },

    {
        id = "deadblip",
        displayName = "10-11",
        icon = "#police-dead",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (isDead and Data.job ~= nil and (Data.job.name == "police" or Data.job.name == "ambulance"))
        end,
        subMenus = { "esx_outlawalert:deadofficerinprogress"}
    },

    {
        id = "news",
        displayName = "News",
        icon = "#news",
        enableMenu =function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and (Data.job.name == "reporter" or Data.job.name == "weaponary"))
        end,
        subMenus = { "news:boom", "news:mic", "news:cam" }
    },

    {
        id = "ems",
        displayName = "Ambulance",
        icon = "#medic",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "ambulance")
        end,
        subMenus = { 'police:drag', 'ems:heal',  'ems:putinvehicle','ems:unseatvehicle','ems:toggleduty', 'ems:status'}
    },

    {
        id = "ems",
        displayName = "Doctor",
        icon = "#medic",
        enableMenu = function()
            local Data = QBCore.Functions.GetPlayerData()
            return (not Data.metadata["isdead"] and not Data.metadata["inlaststand"] and Data.job ~= nil and Data.job.name == "ems")
        end,
        subMenus = { 'police:drag', 'ems:revive', 'ems:heal',  'ems:putinvehicle','ems:unseatvehicle','ems:toggleduty', 'ems:status'}
    },
	
	--Open Garage:
	{
	id = "opengarage",
	title = 'Open Garage',
	icon = '#mj-garage-open',
	type = 'client',
	event = 'MojiaGarages:client:openGarage',
	enableMenu = function()
		PlayerData = QBCore.Functions.GetPlayerData()
		local isingarage, canStoreVehicle = exports["MojiaGarages"]:IsInGarage()
		if not PlayerData.metadata['ishandcuffed'] and not PlayerData.metadata['inlaststand'] and not PlayerData.metadata['isdead'] and not IsPauseMenuActive() and isingarage then 
			local ped = PlayerPedId()
			if not IsPedInAnyVehicle(ped, false) then
				return true
			end
		end
		return false
	end
	},
	
	--Store Vehicle:
	{
	id = "storeVehicle",
	title = 'Store Vehicle',
	icon = '#mj-parking',
	type = 'client',
	event = 'MojiaGarages:client:storeVehicle',
	enableMenu = function()
		PlayerData = QBCore.Functions.GetPlayerData()
		local isingarage, canStoreVehicle = exports["MojiaGarages"]:IsInGarage()
		if not PlayerData.metadata['ishandcuffed'] and not PlayerData.metadata['inlaststand'] and not PlayerData.metadata['isdead'] and not IsPauseMenuActive() and isingarage and canStoreVehicle then 
			local ped = PlayerPedId()
			local pos = GetEntityCoords(ped)
			local ped = PlayerPedId()
			local veh = QBCore.Functions.GetClosestVehicle(pos)
			if IsPedInAnyVehicle(ped) then
				veh = GetVehiclePedIsIn(ped)
			end
			if exports["MojiaVehicleKey"]:CheckHasKey(veh) then
				return true
			end
		end
		return false
	end
	}
}`

**Comment by BlueSky-fur** [comment]
quick Update, i now use your RadialMenu and there it detects garages, but as soon as i press on "Open Garage" the radialmenu closes but nothing pops up i do have cars in my garage tho

**Comment by hoangducdt** [comment]
you need to delete the old garage and create a new one, because the old garage will use different data from this new one, in the radial menu replace exports["MojiaVehicleKey"]:CheckHasKey(veh) with the car key check script that you're using, that's just an example

**Comment by BlueSky-fur** [comment]
Okay.. hmm. ill try in a sec, we use the default qb-vehiclekeys script, but another question, since we implemented your script we cant create houses in general anymore. no errors at all.

**Comment by BlueSky-fur** [comment]
> you need to delete the old garage and create a new one, because the old garage will use different data from this new one, in the radial menu replace exports["MojiaVehicleKey"]:CheckHasKey(veh) with the car key check script that you're using, that's just an example

wait, why would we need to re-create all the garages, your script loads the polyzone for the public garages just fine

**Comment by hoangducdt** [comment]
> > you need to delete the old garage and create a new one, because the old garage will use different data from this new one, in the radial menu replace exports["MojiaVehicleKey"]:CheckHasKey(veh) with the car key check script that you're using, that's just an example
> 
> wait, why would we need to re-create all the garages, your script loads the polyzone for the public garages just fine

because the entire garage shares an array Garages = {} so every time there is a change it is necessary to reload the array

**Comment by hoangducdt** [comment]
Send me your qb-vehiclekeys, qb-houses and radialmenu via my discord #2240, I can watch it when I have free time

**Comment by BlueSky-fur** [comment]
Okay! ill re-implement the whole code and then send you my files on discord. ill add you in the meantime.

**Comment by BlueSky-fur** [comment]
you btw only send your discord tag, i need the name infront of it too ^^

**Comment by BlueSky-fur** [comment]
Uhm, your latest radialmenu update broke it, completly unmodified it doesnt open.
https://i.gyazo.com/d39ba882c78266f3642e4d60d8d2e702.png

**Comment by WrecksBG** [comment]
i think garages and radialmenu its working for your modified core but not for original qb-core if you make it work for qb-core will be perfect but with all depencies qb-houses qb-vehiclekeys garages and radialmenu because there have some problems which u modified for you but not working for us

**Comment by BlueSky-fur** [comment]
> 

he had an error in the radialmenu config im fixing it rn

**Comment by WrecksBG** [comment]
problem with me is i cant store owned vehicle

**Comment by BlueSky-fur** [comment]
where do we even store them? i can open the garage now, but no option to store

**Comment by BlueSky-fur** [comment]
and i also dont have the vehicle keys anymore, yikes.

**Comment by WrecksBG** [comment]
yep same problem with me whole problem with garages come from vehiclekeys

**Comment by BlueSky-fur** [comment]
So basically as an overview for @hoangducdt 

Garages finally work. 

we are unable to unlock or park the vehicles tho since you use a keysystem that we dont have, and we cant change it since qb-vehiclekeys dont has any exports.

**Comment by WrecksBG** [comment]
did you try policegarage i can open but there no have vehicles

**Comment by BlueSky-fur** [comment]
we dont use policegarage, im only interested in the general garages. it would be soo awesome but the vehiclekey thing just sucks currently :/

**Comment by hoangducdt** [comment]
on qb-vehiclekeys:
```
local function HasVehicleKey(plate)
	QBCore.Functions.TriggerCallback('vehiclekeys:server:CheckHasKey', function(result)
		if result then
			HasVehicleKey = true
		else
			HasVehicleKey = false
		end
	end, plate)
	return HasVehicleKey
end
exports('HasVehicleKey', HasVehicleKey)
```

and use:
```
plate = QBCore.Functions.GetPlate(veh)
 if exports["qb-vehiclekeys"]:HasVehicleKey(plate) then
```

**Comment by BlueSky-fur** [comment]
in wich file should we use 

`plate = QBCore.Functions.GetPlate(veh)
 if exports["qb-vehiclekeys"]:HasVehicleKey(plate) then`

sorry am tired

**Comment by hoangducdt** [comment]
In the F1 menu I'm just asking you to add events to your menu, I'm not asking you to use my example, it's an example that one example can't run on all menu types

**Comment by WrecksBG** [comment]
BlueSky give me your discord to see did we can help each other

**Comment by hoangducdt** [comment]
> in wich file should we use
> 
> `plate = QBCore.Functions.GetPlate(veh) if exports["qb-vehiclekeys"]:HasVehicleKey(plate) then`
> 
> sorry am tired

replace exports["MojiaVehicleKey"]:CheckHasKey(veh) with exports["qb-vehiclekeys"]:HasVehicleKey(plate)

**Comment by hoangducdt** [comment]
This garage is built on qb-core base, it works properly without car key script and no matter what radial menu you are using what you need to do is add the event to the menu F1 and add the car key check of the scenario you're using if you want it to be perfect.

**Comment by BlueSky-fur** [comment]
it gets more and more confusing, first you say **use** 
`plate = QBCore.Functions.GetPlate(veh)
 if exports["qb-vehiclekeys"]:HasVehicleKey(plate) then`

then you say dont use it its an example, im absolutely confused now.

**Comment by BlueSky-fur** [comment]
can you maybe just shave an qb-vehiclekeys file? no matter what i try, it wont do what its supposed to do. its still confusing as you say your garage system is based of qb-garage, if that was then the default key script should work in theory

**Comment by WrecksBG** [comment]
now i have vector4 error ... how u fix it ?

**Comment by BlueSky-fur** [comment]
> now i have vector4 error ... how u fix it ?

i just updated all files again. 

did you manage to make the vehicle key thing work?

**Comment by WrecksBG** [comment]
i cant check because script its not working with this error i download again radialmenu, garages and clipboard and have this error

**Comment by BlueSky-fur** [comment]
id suggest you open your own issue at that point so stuff in here doesnt get more cluttered as it allready is

**Comment by hoangducdt** [comment]
You need to recreate the apartment garage, the old garage’s data will not be compatible with this garage, I'm not associated with qb-vehiclekeys and qb-radialmenu because I want to give users more options, you shouldn't put too much attention into my car key scenario and menu, choose according to your available script! on qb-radialmenu you don't even need to care about activation or hidden menus, and that means you don't need a car key script either

**Comment by BlueSky-fur** [comment]
we cant unlock cars that are pulled out of the garage tho.

**Comment by BlueSky-fur** [comment]
and im out of options. i cant imagine of a reason why.

**Comment by WrecksBG** [comment]
now its working but when i create house i cant buy dont have buy option

**Comment by NocityRP** [comment]
> you btw only send your discord tag, i need the name infront of it too ^^

Hi, did you get a fix for the console error?

**Comment by BlueSky-fur** [comment]
> now its working but when i create house i cant buy dont have buy option

create the house. switch job, walk a bit away from it, and back to it

**Comment by BlueSky-fur** [comment]
> You need to recreate the apartment garage, the old garage’s data will not be compatible with this garage, I'm not associated with qb-vehiclekeys and qb-radialmenu because I want to give users more options, you shouldn't put too much attention into my car key scenario and menu, choose according to your available script! on qb-radialmenu you don't even need to care about activation or hidden menus, and that means you don't need a car key script either

quick Update.

i am deeply sorry, it was my code editor that messed up the lines when commiting to the github repo we use, it works completly fine now, extremly nice and lowperformance script. thank you so much for releasing it for free! and sorry for wasting your time! ill recogment the resource on my twitch the next time i go live as a way to say sorry!
