### ISSUE TITLE
[Issue] - bad argument #1 to 'vector4'

### ISSUE THREAD

**Issue by NocityRP** [hoangducdt/MojiaGarages#23]
How do I fix this, I have followed all the steps with the README?

**Comment by hoangducdt** [comment]
**Important Note:**
All garage data of pre-existing homes will not be compatible with this garage, you need to delete those garages and create new ones. When creating a new garage, you need to be on a vehicle.

**Comment by NocityRP** [comment]
> **Important Note:** All garage data of pre-existing homes will not be compatible with this garage, you need to delete those garages and create new ones. When creating a new garage, you need to be on a vehicle.

So, I need to recreate all the garages? that I made in the config?

**Comment by hoangducdt** [comment]
> > **Important Note:** All garage data of pre-existing homes will not be compatible with this garage, you need to delete those garages and create new ones. When creating a new garage, you need to be on a vehicle.
> 
> So, I need to recreate all the garages? that I made in the config?

Data on sql `houselocations`, not in config

**Comment by hoangducdt** [comment]
goto `houselocations` >> `garage`  delete the data there, then go to that house and recreate the garage in the usual way, or better yet delete all the house data and start over
