### ISSUE TITLE
[Issue] - Nothing showing when using Radial Menu

### ISSUE THREAD

**Issue by NocityRP** [hoangducdt/MojiaGarages#26]
I have updated everything, and ensured that it all works, but now the menu isn't showing when using the radial menu, I haven't tried using your radial menu, as I want to use the one I have. What would be the problem?

**Comment by hoangducdt** [comment]
show your menu event

**Comment by NocityRP** [comment]
I've tried both 'MojiaGarages:client:openGarage' and I've also tried 'MojiaGarages:openGarage'. Neither of them have worked.

**Comment by BlueSky-fur** [comment]
i had issues with every radialmenu i found, grabbed hoang's one works like a charm and its easy to adapt to it, is fairly better than the default qb one

**Comment by NocityRP** [comment]
> i had issues with every radialmenu i found, grabbed hoang's one works like a charm and its easy to adapt to it, is fairly better than the default qb one

I just want to use the radial menu I have as I have added sections, and don't really want to change it

**Comment by hoangducdt** [comment]
I don't know what your problem is, this is what I do on the original QB-core, it works fine and no errors, you can watch the video: https://youtu.be/C01WwrdL670
