### ISSUE TITLE
[BUG] issues polyzone house garages

### ISSUE THREAD

**Issue by xenfovn** [hoangducdt/MojiaGarages#27]
![image](https://user-images.githubusercontent.com/55439243/147512604-96fedc44-d46b-4203-bc9d-8814889bb8d1.png)
![image](https://user-images.githubusercontent.com/55439243/147512639-ec3ea491-1991-468d-9ec9-6df25ea282c3.png)

polyzone quá nhỏ , khi cất xe ped chỉ cần vô tình đi ra ngoài là coi như mất xe , nên tăng thêm khoảng cách

**Comment by xenfovn** [comment]
lỗi áp dụng cho bất kì garages nào , khi cất xe ped sẽ bị đẩy ra ngoài , nên poly không thể get ped trong khu vực nào

**Comment by xenfovn** [comment]
![image](https://user-images.githubusercontent.com/55439243/147512921-a49429b1-afb7-4fab-b4e5-03bc3ad16ed4.png)
với lại cái này không cần thiết , có thể bỏ đi cũng được

**Comment by hoangducdt** [comment]
> ![image](https://user-images.githubusercontent.com/55439243/147512921-a49429b1-afb7-4fab-b4e5-03bc3ad16ed4.png) với lại cái này không cần thiết , có thể bỏ đi cũng được

rồi bọn nó tạo nhà kiểu gì? nếu có event trong menu f1 thì có thể tạo bình thường, không có cái không có lệnh sao nó tạo ông

**Comment by hoangducdt** [comment]
> ![image](https://user-images.githubusercontent.com/55439243/147512604-96fedc44-d46b-4203-bc9d-8814889bb8d1.png) ![image](https://user-images.githubusercontent.com/55439243/147512639-ec3ea491-1991-468d-9ec9-6df25ea282c3.png)
> 
> polyzone quá nhỏ , khi cất xe ped chỉ cần vô tình đi ra ngoài là coi như mất xe , nên tăng thêm khoảng cách

local x1 = QBCore.Shared.Round(pos.x + (forward.x * (3.0)) + (right.x * (2.0)), 2)
local y1 = QBCore.Shared.Round(pos.y + (forward.y * (3.0)) + (right.y * (2.0)), 2)
local x2 = QBCore.Shared.Round(pos.x + (forward.x * (-3.0)) + (right.x * (2.0)), 2)
local y2 = QBCore.Shared.Round(pos.y + (forward.y * (-3.0)) + (right.y * (2.0)), 2)
local x3 = QBCore.Shared.Round(pos.x + (forward.x * (-3.0)) + (right.x * (-2.0)), 2)
local y3 = QBCore.Shared.Round(pos.y + (forward.y * (-3.0)) + (right.y * (-2.0)), 2)
local x4 = QBCore.Shared.Round(pos.x + (forward.x * (3.0)) + (right.x * (-2.0)), 2)
local y4 = QBCore.Shared.Round(pos.y + (forward.y * (3.0)) + (right.y * (-2.0)), 2)
để tăng giá trị này lên, tôi để vừa khung cái xe là vì sợ nhà cạnh nhau tạo gara nhiều khi ko để ý nó chồng lên nhau á

**Comment by hoangducdt** [comment]
> ![image](https://user-images.githubusercontent.com/55439243/147512604-96fedc44-d46b-4203-bc9d-8814889bb8d1.png) ![image](https://user-images.githubusercontent.com/55439243/147512639-ec3ea491-1991-468d-9ec9-6df25ea282c3.png)
> 
> polyzone quá nhỏ , khi cất xe ped chỉ cần vô tình đi ra ngoài là coi như mất xe , nên tăng thêm khoảng cách

![image](https://user-images.githubusercontent.com/32219904/147516145-7f11703e-5515-4a79-a01d-f015d9871a8c.png)
Đã fix lỗi này nha! test thuwr xem :D

**Comment by xenfovn** [comment]
góp ý nhé . nên tạo 1 path để test sau đó mới hợp nhất vô nhánh chính tránh lỗi
