### ISSUE TITLE
[Bug] I know this was intended but hear me out.

### ISSUE THREAD

**Issue by ImpulseFPS** [hoangducdt/MojiaGarages#29]
So great work on the garage system.
But the impound the fact that player can total his vehicle goes to impound and pull it out again or for example, someone throws the other player car into the ocean the player is like "aight bet" just goes to impound and pulls it out again you see what I mean?
This method can be abused in so many ways and there is no limit to it

**Comment by ImpulseFPS** [comment]
> So great work on the garage system. But the impound the fact that player can total his vehicle goes to impound and pull it out again or for example, someone throws the other player car into the ocean the player is like "aight bet" just goes to impound and pulls it out again you see what I mean? This method can be abused in so many ways and there is no limit to it

The solution to this would be to catch all the vehicles taken out of impound and then check if the vehicle is already out if true notify the player that the vehicle is out else spawn the vehicle

**Comment by hoangducdt** [comment]
Oh great idea and I never thought of this! I will research the solution, because this involves quite a few problems for example a car when out of sight it will automatically put in storage for example! I can make it look like the car is outside, each time it will automatically save the coordinates to sql then when the player enters the game it will automatically appear at the last place it stopped, before I did this on ESX but with QB I haven't had time to do it yet

**Comment by ImpulseFPS** [comment]
So the solution to the server restart- vehicle should end up in impound tho.
Solution for player reconnecting to the server to rest the vehicle should not be a problem if you catch data on the server-side.
You have an example for this in like OLD qb-garage before any code change was made to it.
when out of sight you can just use the server-side catch for it no?
Btw so i dont spam the issue when its "not" could you add me on discord ImpulseFPS#3613

**Comment by hoangducdt** [comment]
If there is any idea you can pull, any pull request is welcome

**Comment by ImpulseFPS** [comment]
ill see what i can do

**Comment by BlueSky-fur** [comment]
> 

do you mean by that that basically vehicles are persistent where we leave them regardless of if we disconnect?

**Comment by ImpulseFPS** [comment]
No the game logic would still delete the vehicle but now we have the way to get them back in caae they are gone

**Comment by ImpulseFPS** [comment]
FIXED with the latest commit. @hoangducdt BEAST
