### ISSUE TITLE
[đề xuất] loại bỏ khả năng có thể lấy một chiếc xe ở tất cả garages

### ISSUE THREAD

**Issue by xenfovn** [hoangducdt/MojiaGarages#3]
hiện tại : khi bạn cất xe ở garages trung tâm , bạn có thể đến garages khác để lấy chiếc xe đó , bạn có thể sửa chữa lại điều này không ?

**Comment by hoangducdt** [comment]
Ở bản mới nhất đã có chức năng này rồi nhé!
