### ISSUE TITLE
Issue with qb-houses

### ISSUE THREAD

**Issue by WrecksBG** [hoangducdt/MojiaGarages#30]
i create house and if i want to see option for buy i have to logout. When i join again i can buy house and when i buy i cant enter in and didnt show me garage which i was add before. I have to restart whole server and then everything is fine (like he didnt update in real time)

**Comment by hoangducdt** [comment]
basically the edits are only related to the house and garage name and not to the other things of the house, so I don't think this is the fault of the garage

**Comment by xenfovn** [comment]
true , issues in qb-house , pls wait new major update 1/2022

**Comment by ImpulseFPS** [comment]
> 

i don't have the issue and im on the latest qb-houses. he is prob running an older version of qb-houses or he is trying to buy a house with a real estate job..

**Comment by WrecksBG** [comment]
I use latest qb house and create house with real estate job after that change job to unemployed and can't buy I still see real estate functions. When I reblog I can buy the house but I can't enter I have to restart the server and then everything is fine

**Comment by xenfovn** [comment]
https://github.com/qbcore-framework/qb-houses/pull/113/files
fixed with pr
