### ISSUE TITLE
Sell Vehicle issue

### ISSUE THREAD

**Issue by KenanDK666** [hoangducdt/MojiaGarages#31]
When i'm trying to sell my vehicle at the used vehicle sales lot nothing happens with either option so resell you vehicle.
i'm getting no errors in the console at all.

**Comment by xenfovn** [comment]
change event check owner in qb-vehiclesales

**Comment by KenanDK666** [comment]
iim not that good in coding so i would appriciate a more specific answer, since i followed his tutorial just to get it to work.

**Comment by KenanDK666** [comment]
im not that good in coding so i would appriciate a more specific answer, since i followed his tutorial just to get it to work.

**Comment by SoCallMeAstro** [comment]
In qb-vehiclesales > client at line 282 and 352 change `qb-garage:server:checkVehicleOwner` to `MojiaGarages:server:checkVehicleOwner`!
