### ISSUE TITLE
Is the police garage functioning?

### ISSUE THREAD

**Issue by zeemkarry** [hoangducdt/MojiaGarages#32]
hi,
police personal garage is working fine. I can store my personal car in police garage.
but I don't see any job cars in the job garage.
picture for reference link [https://imgur.com/DH9xkY9](https://imgur.com/DH9xkY9)

**Comment by ImpulseFPS** [comment]
you need to use diff export to get job garage to work

**Comment by zeemkarry** [comment]
Thanks, I added it in the radial menu
