### ISSUE TITLE
[Issue] - /impound

### ISSUE THREAD

**Issue by NocityRP** [hoangducdt/MojiaGarages#33]
When the police impound the car, it's not showing in the impound, no F8 error, nor any Console errors!

**Comment by hoangducdt** [comment]
https://streamable.com/0z6181

**Comment by NocityRP** [comment]
> https://streamable.com/0z6181

Hello, would you be able to send me your qb-police job script, as when I do /impound I’m getting nothing. Thank you! I’m also on the latest build of the garages.

**Comment by hoangducdt** [comment]
> > https://streamable.com/0z6181
> 
> Hello, would you be able to send me your qb-police job script, as when I do /impound I’m getting nothing. Thank you! I’m also on the latest build of the garages.

that's the default qb-policejob: https://github.com/qbcore-framework/qb-policejob

**Comment by xenfovn** [comment]
tested no problem , make sure u using qb-core && qb-policejob latest version

**Comment by NocityRP** [comment]
> > > https://streamable.com/0z6181
> > 
> > 
> > Hello, would you be able to send me your qb-police job script, as when I do /impound I’m getting nothing. Thank you! I’m also on the latest build of the garages.
> 
> that's the default qb-policejob: https://github.com/qbcore-framework/qb-policejob

When I’m back on Sunday I will update and test, and let you know. The last the I’m aware of is that’s it’s the latest but clearly not.
