### ISSUE TITLE
[Issue] - Updated the script and getting this?

### ISSUE THREAD

**Issue by NocityRP** [hoangducdt/MojiaGarages#39]

**Comment by NocityRP** [comment]
![image](https://user-images.githubusercontent.com/93712286/148655336-7789a3c2-f4ce-46e1-aada-aad3d529cbb8.png)

**Comment by NocityRP** [comment]
![image](https://user-images.githubusercontent.com/93712286/148655831-6039cae6-4148-402c-94ef-f9656fd25342.png)

**Comment by hoangducdt** [comment]
Old vehicles don't have data on the database, you can take the data of a new vehicle and put it in the old vehicle data, and set all old vehicle in some garage, then you can get them out of that garage.

**Comment by NocityRP** [comment]
> Old vehicles don't have data on the database, you can take the data of a new vehicle and put it in the old vehicle data, and set all old vehicle in some garage, then you can get them out of that garage.

Got rid of the cars and now getting this...
![image](https://user-images.githubusercontent.com/93712286/148657247-185609c2-44ca-4c49-9c37-724f82e161de.png)

**Comment by NocityRP** [comment]
> Old vehicles don't have data on the database, you can take the data of a new vehicle and put it in the old vehicle data, and set all old vehicle in some garage, then you can get them out of that garage.

and also getting this...
![image](https://user-images.githubusercontent.com/93712286/148657264-3063cfb8-6f4c-45ec-9f32-97bc73d29210.png)

**Comment by h3ftyTV** [comment]
oh, so on a live server i cant really use the update :S
Or i need all players to get there car from  one garage... uff aint going to make me there fav :D

**Comment by hoangducdt** [comment]
> oh, so on a live server i cant really use the update :S Or i need all players to get there car from one garage... uff aint going to make me there fav :D

This update should not be used on an existing server, because the old database is incomplete for this new version! This update is only good for a brand new database

**Comment by NocityRP** [comment]
> > oh, so on a live server i cant really use the update :S Or i need all players to get there car from one garage... uff aint going to make me there fav :D
> 
> This update should not be used on an existing server, because the old database is incomplete for this new version! This update is only good for a brand new database

So If I delete everything in the player_vehicles it will work then just add your update?

**Comment by hoangducdt** [comment]
> > > oh, so on a live server i cant really use the update :S Or i need all players to get there car from one garage... uff aint going to make me there fav :D
> > 
> > 
> > This update should not be used on an existing server, because the old database is incomplete for this new version! This update is only good for a brand new database
> 
> So If I delete everything in the player_vehicles it will work then just add your update?

you need an empty database, download the update and run the sql.sql file and you're done! there have been successful people running before with no problem you can see [issues#38](https://github.com/hoangducdt/MojiaGarages/issues/38)

**Comment by NocityRP** [comment]
> > > > oh, so on a live server i cant really use the update :S Or i need all players to get there car from one garage... uff aint going to make me there fav :D
> > > 
> > > 
> > > This update should not be used on an existing server, because the old database is incomplete for this new version! This update is only good for a brand new database
> > 
> > 
> > So If I delete everything in the player_vehicles it will work then just add your update?
> 
> you need an empty database, download the update and run the sql.sql file and you're done! there have been successful people running before with no problem you can see [issues#38](https://github.com/hoangducdt/MojiaGarages/issues/38)

Just done everything cleaned the player_vehicles, and still getting this...

![image](https://user-images.githubusercontent.com/93712286/148658332-521921d0-e8ae-4354-babb-6fa2a04192db.png)

**Comment by NocityRP** [comment]
> > > > > oh, so on a live server i cant really use the update :S Or i need all players to get there car from one garage... uff aint going to make me there fav :D
> > > > 
> > > > 
> > > > This update should not be used on an existing server, because the old database is incomplete for this new version! This update is only good for a brand new database
> > > 
> > > 
> > > So If I delete everything in the player_vehicles it will work then just add your update?
> > 
> > 
> > you need an empty database, download the update and run the sql.sql file and you're done! there have been successful people running before with no problem you can see [issues#38](https://github.com/hoangducdt/MojiaGarages/issues/38)
> 
> Just done everything cleaned the player_vehicles, and still getting this...
> 
> ![image](https://user-images.githubusercontent.com/93712286/148658332-521921d0-e8ae-4354-babb-6fa2a04192db.png)

This is also coming with it after following the issues#38

**Comment by hoangducdt** [comment]
What columns does your player_vehicles database have?

**Comment by NocityRP** [comment]
> What columns does your player_vehicles database have?

![image](https://user-images.githubusercontent.com/93712286/148658784-b67abae4-bdf0-4431-b93e-f3f2fc4bf40b.png)

This are the database columns

**Comment by hoangducdt** [comment]
issues#38 has been merged you just need to add the event in qb-vehiclekey mentioned in the readme

**Comment by NocityRP** [comment]
> issues#38 has been merged you just need to add the event in qb-vehiclekey mentioned in the readme

Added everything, the database is clean I will restart the server and let you know if it's fixed the problem.

Also other scripts have stopped working that I added the garage would I be able to get help with making them work again?

**Comment by hoangducdt** [comment]
the newly added sql are brand new columns that are not related to the old columns already there, i don't know what is the problem you are having here 🤔 See its function on the error line try what it does

**Comment by NocityRP** [comment]
> the newly added sql are brand new columns that are not related to the old columns already there, i don't know what is the problem you are having here 🤔 See its function on the error line try what it does

No Still not working...
![image](https://user-images.githubusercontent.com/93712286/148660228-5d6974f4-5a2e-4475-85be-fad53fed169b.png)

**Comment by hoangducdt** [comment]
I tried on original qb-core framework, everything is fine. Please make sure you are using the latest qb framework: https://streamable.com/sgdw69

**Comment by NocityRP** [comment]
> I tried on original qb-core framework, everything is fine. Please make sure you are using the latest qb framework: https://streamable.com/sgdw69

It's not working, I've got the latest vehiclekeys, latest qb-vehicleshop and the latest qb-core.

**Comment by NocityRP** [comment]
Only thing I'm getting is the no default value...
![image](https://user-images.githubusercontent.com/93712286/148665666-84977c01-7527-4228-aae8-099df99d7513.png)
