### ISSUE TITLE
[Issue] - (global 'cleanUpThresholdTime')

### ISSUE THREAD

**Issue by NocityRP** [hoangducdt/MojiaGarages#41]
![image](https://user-images.githubusercontent.com/93712286/148698960-4b7245bd-4bcf-42b2-ac64-17ce776d74e2.png)

**Comment by hoangducdt** [comment]
![image](https://user-images.githubusercontent.com/32219904/148699088-29c6d954-83f5-497b-a85c-1a422c0b4a3c.png)
Are you sure you have all the updates?

**Comment by NocityRP** [comment]
> ![image](https://user-images.githubusercontent.com/32219904/148699088-29c6d954-83f5-497b-a85c-1a422c0b4a3c.png) Are you sure you have all the updates?

Alright Thank you fixed that error, now getting this? 

![image](https://user-images.githubusercontent.com/93712286/148699198-42cc946e-581c-4195-b85b-106e5c36e62c.png)

**Comment by NocityRP** [comment]
I have fixed all the error, only problem now is when the car gets DV it doesn't go to the depot...

**Comment by NocityRP** [comment]
Also when you press track, it's saying your vehicle has been marked, and just showing this?

![image](https://user-images.githubusercontent.com/93712286/148700196-95725558-3971-49f5-9376-7e600854212a.png)

**Comment by hoangducdt** [comment]
You should download the whole file, not update each file

**Comment by hoangducdt** [comment]
> Also when you press track, it's saying your vehicle has been marked, and just showing this?
> 
> ![image](https://user-images.githubusercontent.com/93712286/148700196-95725558-3971-49f5-9376-7e600854212a.png)

it will mark where the car stops if it is outside

**Comment by NocityRP** [comment]
> > Also when you press track, it's saying your vehicle has been marked, and just showing this?
> > ![image](https://user-images.githubusercontent.com/93712286/148700196-95725558-3971-49f5-9376-7e600854212a.png)
> 
> it will mark where the car stops if it is outside

So how do I get the car out of the depot?

Also I have update the files from the whole update, then change the config to my garages rather than the ones you created

**Comment by hoangducdt** [comment]
Only cars with fines greater than 0 can be taken from the depot, and cars located outside the garage will be in the last position where it was stopped. If you rely on this garage to add your own, the mistakes you have made should be resolved on your own, as they are different we don't know where your problem lies.

**Comment by NocityRP** [comment]
> Only cars with fines greater than 0 can be taken from the depot, and cars located outside the garage will be in the last position where it was stopped. If you rely on this garage to add your own, the mistakes you have made should be resolved on your own, as they are different we don't know where your problem lies.

Would it be possible to get the old one back before this update regarding the live tracking?

**Comment by NocityRP** [comment]
> Only cars with fines greater than 0 can be taken from the depot, and cars located outside the garage will be in the last position where it was stopped. If you rely on this garage to add your own, the mistakes you have made should be resolved on your own, as they are different we don't know where your problem lies.

I've got back to the version before the the parking / impound, and now getting this error...

![image](https://user-images.githubusercontent.com/93712286/148703922-edc990c5-32c8-454a-834c-8be59736ed36.png)
