### ISSUE TITLE
[question/help] New SQL update and clientsite error

### ISSUE THREAD

**Issue by stolk88** [hoangducdt/MojiaGarages#45]
I updated you're script for the new sql update.
Maybe i can send you so you can take a look.

Since the last update i get a client side error (clean database and all)
SCRIPT ERROR: @MojiaGarages/client.lua:870: attempt to index a nil value (local 'oldmodifications')
object not a string...

You know what i dit wrong there?

**Comment by hoangducdt** [comment]
show me what's in your mods column

**Comment by stolk88** [comment]
I just removed oldmodifications from the client.lua, everything is working fine till now..

{"modRightFender":-1,"dirtLevel":7.14895411251853,"plateIndex":1,"tyreSmokeColor":[255,255,255],"bodyHealth":1000.0592475178704,"modExhaust":-1,"modCustomTiresF":1,"windowTint":2,"modSpoilers":-1,"modSmokeEnabled":false,"modXenon":1,"modAPlate":-1,"engineHealth":1000.0592475178704,"modStruts":-1,"modArmor":4,"modTrimA":-1,"modTank":-1,"neonColor":[255,0,255],"interiorColor":72,"modFrontWheels":52,"color1":72,"wheelColor":159,"dashboardColor":0,"modSteeringWheel":-1,"modVanityPlate":-1,"modTransmission":2,"modSuspension":3,"modEngine":3,"modWindows":-1,"modSpeakers":-1,"modRearBumper":-1,"modHorns":5,"modDashboard":-1,"modEngineBlock":-1,"modAerials":-1,"modRoof":-1,"wheels":0,"modAirFilter":-1,"neonEnabled":[false,false,false,false],"modDoorSpeaker":-1,"modHydrolic":-1,"modSideSkirt":-1,"plate":"81TLK724","modTrunk":-1,"modHood":-1,"modTrimB":-1,"modBrakes":2,"modTurbo":1,"color2":107,"modSeats":-1,"modLivery":-1,"modPlateHolder":-1,"modFender":-1,"fuelLevel":64.3405870126668,"xenonColor":0,"extras":{"2":true,"3":false,"4":false},"modOrnaments":-1,"tankHealth":4000.2369900714818,"modDial":-1,"model":86306326,"modFrontBumper":-1,"modCustomTiresR":false,"modFrame":-1,"modArchCover":-1,"modBackWheels":-1,"pearlescentColor":156,"modShifterLeavers":-1,"modGrille":-1}

**Comment by stolk88** [comment]
Yes i did, what is gonna be missing by removing oldmodifications?

**Comment by hoangducdt** [comment]
now the data is taken from the mods column instead of the modifications column like before, so the part getting data from the server will change, if you use the old version and update it manually it may be missing somewhere leading to returned data will be wrong. check oldmodifications and modifications to see if the vehicle has changed, if there are changes (distance, fuel, ...) it will update to the database, if this part is missing, the vehicle will not be updated information

**Comment by hoangducdt** [comment]
Help me to check this:
Edit client:
```
RegisterNetEvent('MojiaGarages:client:updateVehicle', function(netId)
	local vehicle = NetworkGetEntityFromNetworkId(netId)
	if (vehicle == nil) then
		return
	end
	local plate = QBCore.Functions.GetPlate(vehicle)
	if NetworkGetEntityIsNetworked(vehicle) and DoesEntityExist(vehicle) then
		QBCore.Functions.TriggerCallback('MojiaGarages:server:checkHasVehicleOwner', function(hasowned)
			if hasowned then					
				QBCore.Functions.TriggerCallback('MojiaGarages:server:getVehicleData', function(VehicleData)
					local networkId = NetworkGetNetworkIdFromEntity(vehicle)
					local modifications = GetVehicleModifications(vehicle)
					if VehicleData then
						local oldmodifications = json.decode(VehicleData.mods)
						local vehpos = GetEntityCoords(vehicle)
						local vehRot = GetEntityRotation(vehicle)
						if oldmodifications.lockstatus and oldmodifications.bodyHealth and oldmodifications.engineHealth and oldmodifications.tankHealth then
							if (#(vector3(VehicleData.posX, VehicleData.posY, VehicleData.posZ) - vehpos) > 1.0 
								or GetRotationDifference(vector3(VehicleData.rotX, VehicleData.rotY, VehicleData.rotZ), vehRot) > 15.0
								or modifications.lockstatus ~= oldmodifications.lockstatus
								or math.abs(modifications.bodyHealth - oldmodifications.bodyHealth) > 5.0
								or math.abs(modifications.engineHealth - oldmodifications.engineHealth) > 5.0
								or math.abs(modifications.tankHealth - oldmodifications.tankHealth) > 5.0
							) then							
								TriggerServerEvent('MojiaGarages:server:updateVehicle', networkId, modifications)
							end
						else
							TriggerServerEvent('MojiaGarages:server:updateVehicle', networkId, modifications)
						end
					else
						TriggerServerEvent('MojiaGarages:server:updateVehicle', networkId, modifications)
					end
				end, plate)
			end
		end, plate)
	end
end)
```

**Comment by stolk88** [comment]
![image](https://user-images.githubusercontent.com/50120962/148991960-829bbb51-c2e6-4b5b-8e79-8bdf7f5e9236.png)


With above it is not saving in the new modificatins. So the modifications database stays empty.

This is in the 'mods' database:
{"modFrame":-1,"modFender":-1,"dashboardColor":0,"modShifterLeavers":-1,"modAerials":-1,"model":86306326,"modTrimB":-1,"modArmor":-1,"modTurbo":false,"modSmokeEnabled":false,"modArchCover":-1,"modHood":-1,"modAirFilter":-1,"bodyHealth":1000.0592475178704,"modSeats":-1,"modSpoilers":-1,"modLivery":-1,"fuelLevel":64.3405870126668,"modBrakes":-1,"modSpeakers":-1,"modSideSkirt":-1,"modStruts":-1,"modDashboard":-1,"plateIndex":1,"pearlescentColor":156,"modTrimA":-1,"wheelColor":0,"modSteeringWheel":-1,"modPlateHolder":-1,"modEngineBlock":-1,"modTrunk":-1,"tyreSmokeColor":[255,255,255],"modWindows":-1,"modHorns":-1,"modCustomTiresR":false,"modXenon":false,"modTransmission":-1,"modTank":-1,"dirtLevel":0.0,"modSuspension":3,"wheels":0,"modDoorSpeaker":-1,"windowTint":2,"modRearBumper":-1,"neonColor":[255,0,255],"modDial":-1,"modCustomTiresF":false,"modExhaust":-1,"modRoof":-1,"modRightFender":-1,"modVanityPlate":-1,"extras":{"2":true,"3":false,"4":false},"plate":"03JVW662","modEngine":-1,"modHydrolic":-1,"modGrille":-1,"interiorColor":4,"modOrnaments":-1,"modFrontBumper":-1,"modBackWheels":-1,"modAPlate":-1,"color1":72,"modFrontWheels":-1,"xenonColor":255,"color2":0,"neonEnabled":[false,false,false,false],"engineHealth":1000.0592475178704,"tankHealth":4000.2369900714818}

**Comment by stolk88** [comment]
Is there a way to let the script know that you are the owner of multiple vehicles (after server reset)
And if i may ask what vehiclekey script are you using?
qb-vehiclekeys is almost the only thing holding me back with this =P

**Comment by stolk88** [comment]
qb-vehiclekeys/client/main.lua

This fixed only beeing able to unlock 1 owned car after restarting the server for me:

local function LockVehicle()
    local ped = PlayerPedId()
    local pos = GetEntityCoords(ped)
    local veh = QBCore.Functions.GetClosestVehicle(pos)
    local plate = QBCore.Functions.GetPlate(veh)
    local vehpos = GetEntityCoords(veh)
    if IsPedInAnyVehicle(ped) then
        veh = GetVehiclePedIsIn(ped)
    end
    if veh ~= nil and #(pos - vehpos) < 7.5 then
        -- QBCore.Functions.TriggerCallback('vehiclekeys:server:CheckHasKey', function(result)
        QBCore.Functions.TriggerCallback('MojiaGarages:server:checkHasVehicleOwner', function(result)
            if result then
