### ISSUE TITLE
mỗi khi e lấy xe ra nó đều không còn xăng hay động cơ gì hết bác ạ 

### ISSUE THREAD

**Issue by mrshenno1** [hoangducdt/MojiaGarages#46]
![image](https://user-images.githubusercontent.com/52213471/148961716-0153447a-c765-4fec-a1a6-aa7b9c6546a6.png)
mỗi khi e lấy xe ra nó đều không còn xăng hay động cơ gì hết bác ạ 
![image](https://user-images.githubusercontent.com/52213471/148961836-f3c9b1a6-c69a-4c5b-bc95-76566d723c9e.png)

**Comment by hoangducdt** [comment]
Kiểm tra xem dữ liệu có được lưu vào database không

**Comment by mrshenno1** [comment]
![image](https://user-images.githubusercontent.com/52213471/148972732-7915cf66-b3e3-4a7c-8075-d3772273b84d.png
 vẫn lưu bth bác ạ nó ko đọc đc sql

**Comment by mrshenno1** [comment]
bác có link discord ko bác cho e vào với

**Comment by hoangducdt** [comment]
sáng mai nhé! giờ đi làm rồi

**Comment by mrshenno1** [comment]
có gì bác cho e xin link dis của bác nhé

**Comment by mrshenno1** [comment]
bản qb-core của e là bản cũ hay sao ý bác nó đang ko đọc đc sang bác ạ

**Comment by mrshenno1** [comment]
bác còn đó ko bác

**Comment by mrshenno1** [comment]
![image](https://user-images.githubusercontent.com/52213471/149074050-bb98a0d6-2cf2-4be8-b439-f6d4cb2e8e6d.png)
bác ơi giờ trong game đọc 1 kiểu mà sql nó lại ko nhận từ game vào sql là sao bác nhỉ
![image](https://user-images.githubusercontent.com/52213471/149074151-1f90c376-83d6-467e-9798-02acb8c76873.png)
