### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by stolk88** [hoangducdt/MojiaGarages#49]
What vehiclekey script are you using?
I'm fighting with qb-vehiclekeys for a year now...

The qb-radialmenu scripts works perfect, the only thing i have to do for it to work is restart the resource after server restart..
Do you know a quickfix for the added piece of script?

**Comment by hoangducdt** [comment]
Check new update

**Comment by stolk88** [comment]
Thanks AGAIN, you are a boss!
