### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by DaShizz** [hoangducdt/MojiaGarages#52]
So, when you try to buy a car from the vehicleshop it presents with the following error
https://puu.sh/ICvyu.png
and the vehicle doesn't get saved in the DB
when you try to /admincar any car it gives an error referring to the columns that we added in the new SQL that was attached to the script saying field 'modifications' doesn't have a default value.

**Comment by IdrisDose** [comment]
Remove column modifications from your player_vehicles.
