### ISSUE TITLE
PolyZone error

### ISSUE THREAD

**Issue by DaShizz** [hoangducdt/MojiaGarages#53]
when you are under a job that has a station and you change into another job using the setjob command the following print from polyzone keeps repeating itself over and over and over on a loop and it doesn't stop until server restart or /logout https://puu.sh/ICvB7.png

**Comment by hoangducdt** [comment]
> when you are under a job that has a station and you change into another job using the setjob command the following print from polyzone keeps repeating itself over and over and over on a loop and it doesn't stop until server restart or /logout https://puu.sh/ICvB7.png

This is not an error report

**Comment by DaShizz** [comment]
> > when you are under a job that has a station and you change into another job using the setjob command the following print from polyzone keeps repeating itself over and over and over on a loop and it doesn't stop until server restart or /logout https://puu.sh/ICvB7.png
> 
> This is not an error report

Okay.
Why is it looping after job change ? and how to fix it? Cause prior to last update it wasn't there

**Comment by hoangducdt** [comment]
https://github.com/hoangducdt/MojiaGarages/commit/ffb65c6b49e7342d7e3b6603ccb2b0b1aff4f728
