### ISSUE TITLE
Real Life Parking - Cars not spawning, car shows none in garage

### ISSUE THREAD

**Issue by mhnl3** [hoangducdt/MojiaGarages#59]
Cars not spawning, car shows none in garage after either leaving the game or server restart. Parking in garages, etc. works fine until that happens.

**Comment by BlueSky-fur** [comment]
if you dont mind me asking. when you set a GPS location to them when your far away, does the marker also always go to the same spot near vinewood instead of where the car actually is?

**Comment by mhnl3** [comment]
No the locations are the actual last locations. Your issue is not being able to save the positions. We fixed that by setting the defaults for those columns in the table to 0

**Comment by mhnl3** [comment]
> if you dont mind me asking. when you set a GPS location to them when your far away, does the marker also always go to the same spot near vinewood instead of where the car actually is?

After we fixed some other issues, this happened to us as well.

**Comment by mhnl3** [comment]
So some cars spawn, some don't. I don't have keys when I come back in after restart. Get this error:

[    c-scripting-core] InvokeNative: execution failed: Tried to access invalid entity: 159497
[ script:MojiaGarages] SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 159497
[ script:MojiaGarages] > GetVehicleNumberPlateText (GetVehicleNumberPlateText.lua:2)
[ script:MojiaGarages] > TryGetLoadedVehicle (@MojiaGarages/server.lua:74)
[ script:MojiaGarages] > TrySpawnVehicles (@MojiaGarages/server.lua:103)
[ script:MojiaGarages] > fn (@MojiaGarages/server.lua:498)

**Comment by CraftElitezOllie** [comment]
I'm getting the same issue too

**Comment by CraftElitezOllie** [comment]
I think its all vehicles that have a - infront of its hash 
![image](https://user-images.githubusercontent.com/10517362/151063666-7e02b751-a4bf-408d-836a-b208bf997fe9.png)

**Comment by mhnl3** [comment]
I haven't isolated it to that. But I am getting these errors on the phone. Thinking its all database related.

[      script:qb-core] SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:628: attempt to index a nil value (local 'modifications')
[      script:qb-core] > ref (@qb-phone/server/main.lua:628)
[      script:qb-core] > query_default (@oxmysql/dist/server/build.js:16108)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)
[      script:qb-core] 


[      script:qb-core] SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:399: attempt to index a nil value (local 'MetaData')
[      script:qb-core] > ref (@qb-phone/server/main.lua:399)
[      script:qb-core] > query_default (@oxmysql/dist/server/build.js:16108)
[      script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by BlueSky-fur** [comment]
> I haven't isolated it to that. But I am getting these errors on the phone. Thinking its all database related.
> 
> [ script:qb-core] SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:628: attempt to index a nil value (local 'modifications') [ script:qb-core] > ref (@qb-phone/server/main.lua:628) [ script:qb-core] > query_default (@oxmysql/dist/server/build.js:16108) [ script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96) [ script:qb-core]
> 
> [ script:qb-core] SCRIPT ERROR: SCRIPT ERROR: @qb-phone/server/main.lua:399: attempt to index a nil value (local 'MetaData') [ script:qb-core] > ref (@qb-phone/server/main.lua:399) [ script:qb-core] > query_default (@oxmysql/dist/server/build.js:16108) [ script:qb-core] > processTicksAndRejections (node:internal/process/task_queues:96)

Check the latest MojiaGarages ReadMe, "modifications" was removed. its also not in the sql anymore.

**Comment by mhnl3** [comment]
> 

Its the variable modifications = json.decode(v.mods) not the database table

**Comment by mhnl3** [comment]
I fixed my other issues, but still have it where my real life parking cars go poof

**Comment by Joeystrmz** [comment]
This issue is still happening to me too!

**Comment by maguhd** [comment]
same issue with real parking 
![image](https://user-images.githubusercontent.com/54622859/153748661-5940712f-25fa-4468-bae0-969bb86be531.png)

**Comment by hoangducdt** [comment]
You can try again with the latest version
