### ISSUE TITLE
[BUG] chuộc xe nhiều lần

### ISSUE THREAD

**Issue by xenfovn** [hoangducdt/MojiaGarages#6]
xe không tự động update state sau khi lấy từ depot ra , ở phiên bản gốc của qb-garage thì cái này đã được sửa
https://streamable.com/dpgupo

và sau khi chuộc xe ra thì xe không bị hỏng mặc dù đã tắt fix full

**Comment by hoangducdt** [comment]
này là mặc định xe nằm ngoài gara đều có thể lấy được ở kho, nếu bị cảnh sát phạt mới mất tiền chuộc, còn không thì có thể lấy bình thường đó, vụ không hỏng thì để tối về tui coi

**Comment by hoangducdt** [comment]
chưa thêm update tiền phạt về 0 khi chuộc xe =))

**Comment by hoangducdt** [comment]
Sửa lại rồi test thử coi, bên đây chạy ổn nè:
https://streamable.com/9s7du0

**Comment by xenfovn** [comment]
@hoangducdt nên thêm 1 config xe hỏng theo tùy chỉnh , ví dụ khi chuộc xe từ depot ra chỉ còn 30%

**Comment by hoangducdt** [comment]
Nhiều đứa ôm nguyên cái ví dụ thêm event vào menu F1 rồi báo lỗi, chán chả buồn nói, cái menu F1 mỗi đứa dùng một kiểu bỏ cái event vào còn các thứ khác tự mà điều chỉnh đi chứ trời 🙄

**Comment by xenfovn** [comment]
buồn :V
