### ISSUE TITLE
I can't park the vehicle

### ISSUE THREAD

**Issue by Duruteu** [hoangducdt/MojiaGarages#63]
hello could someone help me with this this error is appearing "no such export HasVehiclekey in resource qb-vehiclekeys" and I can no longer park the vehicle in the garage. Can someone help me?
![20220204235643_1](https://user-images.githubusercontent.com/31866110/152628231-04bee317-3664-4b58-88dd-6e29ed87351b.jpg)

**Comment by Duruteu** [comment]
I still have this error does anyone know how to solve it?

**Comment by Duruteu** [comment]
.

**Comment by 12Echo** [comment]
Hey, did you ever figure this out? Same thing is happening to me.
