### ISSUE TITLE
Depot not working ⚒ 

### ISSUE THREAD

**Issue by fukde077** [hoangducdt/MojiaGarages#64]
all events it's worked well but only Depot area not working for me So I have try everything still notworking shall be have any suggestion for me??

**Comment by hoangducdt** [comment]
currently in the depot area you will only be able to pick up the car when it has a fine greater than 0

**Comment by fukde077** [comment]
Of course, sir The car looks very new after being purchased at PDM then I go to the Depot area for a test it's not working as I can open the Depot garage but no car shows up in there.

**Comment by fukde077** [comment]
For example, I have brought the car into the sea then back to depot area still cannot depot car back from the sea.

**Comment by hoangducdt** [comment]
> For example, I have brought the car into the sea then back to depot area still cannot depot car back from the sea.

this is blocked, the vehicle is located where it will stay, the depot can only take the cars that have been fined by the police, and the fine amount is greater than 0

**Comment by hoangducdt** [comment]
if the depot can take all the cars lying outside, then someone throws your car in the sea, you just say ok okay I will go to the depot and get the car out! do you find it absurd?

**Comment by fukde077** [comment]
That right 👉

**Comment by fukde077** [comment]
ahh, I have seen you're purpose already that is realistic and very nice.
