### ISSUE TITLE
LAST UPDATE

### ISSUE THREAD

**Issue by stolk88** [hoangducdt/MojiaGarages#67]
I'm currently using you're latest update.
No more loss of player vehicles works like a charm!!
A true legandary script, and thank you very much!

Right now there is something with duplicating personal cars while realparking.
I think it has something to do with the script working to fast spawning realparked cars?

Even when somebody tries to store there vehicle in a 'normal' garage it happens that there's also a copy left behind.
But that looks like its random and not always happening.

**Comment by hoangducdt** [comment]
I have fixed this now, you can try to see if the problem is solved

**Comment by stolk88** [comment]
Thank you very much!!

**Comment by stolk88** [comment]
![image](https://user-images.githubusercontent.com/50120962/154296731-9b508918-977e-4c65-b210-2da2ef87592d.png)

It looked like it worked but i gues not yet...

**Comment by stolk88** [comment]
I'm trying to force it to happen again, till now it perfectly fine! I will keep you posted, you are damn fast!!!

**Comment by stolk88** [comment]
![image](https://user-images.githubusercontent.com/50120962/154507050-0dca06a0-a4e8-4348-b959-ee78e55d3659.png)
Every time when -- loop to spawn vehicles near players
There is a big spike in cpu usage, is it something  you can fix?

**Comment by hoangducdt** [comment]
Try the latest version I just updated and let me know if the problem is solved or not

**Comment by stolk88** [comment]
I'm gonna test it!
I'm sorry you only hear the negative stuff.
But i'm such a fan of what you made man, true legandary stuff

**Comment by stolk88** [comment]
Sometimes duping still happens (when the server is busy and people drive fast)
It's such a good script man you're a legend, i really love it!
