### ISSUE TITLE
optimizing issue

### ISSUE THREAD

**Issue by AlHsnn** [hoangducdt/MojiaGarages#69]
Hello,
your work is awesome and i think its best Garage script
after last fix
resmon jumps from 0.08 to 0.70 MojiaGarages
it does fixed duplicate vehicles but now game lag

Thank you! we appreciate your work
![image](https://user-images.githubusercontent.com/87451245/154277141-b20bca92-c024-4f2c-ac80-15f2f7ef6b75.png)

**Comment by AlHsnn** [comment]
everytime try to entering vehicle 
![image](https://user-images.githubusercontent.com/87451245/154279700-74b7bb52-519e-4175-ad01-f97fe4102422.png)

is that related?

**Comment by Joeystrmz** [comment]
![image](https://user-images.githubusercontent.com/97709249/154345427-22823f3e-9c7f-477b-a986-feb8ddf62070.png)

**Comment by hoangducdt** [comment]
Try the latest version I just updated and let me know if the problem is solved or not

**Comment by AlHsnn** [comment]
@hoangducdt server laggy after last update
![image](https://user-images.githubusercontent.com/87451245/154565333-8ed2cb14-f33e-4818-b1b5-afda3de7a815.png)
