### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by madalex24** [hoangducdt/MojiaGarages#70]
Ive noticed a few issues and i think they are related to the garage and vehicle keys
![Screenshot 2022-02-16 162314](https://user-images.githubusercontent.com/91700454/154310668-879865ba-1091-42b8-94f0-c73730ed7ef0.png)
![Screenshot 2022-02-16 162421](https://user-images.githubusercontent.com/91700454/154310698-1c5646ff-1d19-4586-adef-0e286c2aeb14.png)

**Comment by RavenFiveM** [comment]
I don't think that's an actual issue with the script, but rather you paste the snippets in a wrong way. It literally on the console that and "end" is missing.  For server side you get a nil value for "Player". Can you check if you are loading "Player" variable somewhere?
