### ISSUE TITLE
[BUG] NULL MODS

### ISSUE THREAD

**Issue by maguhd** [hoangducdt/MojiaGarages#71]
Hello! Sometimes cars get null mods and people can't open the garage because of it.
![image](https://user-images.githubusercontent.com/54622859/154510542-4e1b7a7d-e16e-4ab7-b01d-df2ce4bdd828.png)
![image](https://i.imgur.com/6zvLBoS.png)

**Comment by hoangducdt** [comment]
Try the latest version I just updated and let me know if the problem is solved or not
