### ISSUE TITLE
Bug [CAR SPAWN]

### ISSUE THREAD

**Issue by skrimxyz** [hoangducdt/MojiaGarages#72]
Hi again, after a restart, cars are spawning like that

https://imgur.com/a/s7j8isr

**Comment by maguhd** [comment]
Yes because it does not grab the mods right. And its spawn random cars with random plate number, not the specific plate that's defined in database. Probably on that car you got NULL mods. I opened and issue and waiting for a fix.

**Comment by hoangducdt** [comment]
Try the latest version I just updated and let me know if the problem is solved or not

**Comment by AlHsnn** [comment]
@hoangducdt still duplicating vehicles
![image](https://user-images.githubusercontent.com/87451245/154766911-02988425-a038-4724-8b19-561981694c72.png)

**Comment by skrimxyz** [comment]
> Try the latest version I just updated and let me know if the problem is solved or not

Sometimes duplicate the vehicles
