### ISSUE TITLE
Dear hoangducdt,

### ISSUE THREAD

**Issue by stolk88** [hoangducdt/MojiaGarages#74]
The rollback and bug fixes really helped for the scripts performance it runs much better without the serverlag spikes. 🎉

What i noticed when a player lags out or crashes using there vehicle in game.
The vehicle won't load back in when they rejoin, only when i restart the script it pops back in last real parking location.
It's saved in the database in the right manner tho
(maybe there is something missing in the onplayerload refresh realparking update event?)

The duplication only seems to happen on high polly addon vehicles when the move fast or crash into something.
(maybe change it to save when a person leaves there vehicle?)

More rare but there are also situations when i teleport to a location where a real-parked vehicles is parked that the vehicle dupes.
That only happens when there is a other player around the vehicle.

I wish i could help but this script is to next level for me...  You're a true legend

**Comment by hoangducdt** [comment]
Help me test the latest fix to see if it solves the problem

**Comment by WrecksBG** [comment]
i can help u as well if you need

**Comment by hoangducdt** [comment]
![image](https://user-images.githubusercontent.com/32219904/154990735-b5576ffd-c7ec-42a3-aec3-d1d6275ad9bd.png)
I tested it and it seems fine, but not sure if it works well on other servers

**Comment by hoangducdt** [comment]
> i can help u as well if you need

Very welcome

**Comment by WrecksBG** [comment]
give me your discord because i have and couple questions as well

**Comment by hoangducdt** [comment]
> give me your discord because i have and couple questions as well

it's at the bottom of the readme

**Comment by AlHsnn** [comment]
i was in my vehicle, then disconnect and reconnect again to server
but the vehicle disappeared and did not spawn even tracking lead to same location i left it in

**Comment by stolk88** [comment]
> Help me test the latest fix to see if it solves the problem

I tested this one all evening with around 13 people in the server.
It happend only one time that someone's car vanished, bud i updated the script while people where in the server so, i will keep you posted!

Until now it really looks like it's fixed!

**Comment by hoangducdt** [comment]
> > Help me test the latest fix to see if it solves the problem
> 
> I tested this one all evening with around 13 people in the server. It happend only one time that someone's car vanished, bud i updated the script while people where in the server so, i will keep you posted!
> 
> Until now it really looks like it's fixed!

Is it running fine now?

**Comment by stolk88** [comment]
> > > Help me test the latest fix to see if it solves the problem
> > 
> > 
> > I tested this one all evening with around 13 people in the server. It happend only one time that someone's car vanished, bud i updated the script while people where in the server so, i will keep you posted!
> > Until now it really looks like it's fixed!
> 
> Is it running fine now?

Yes it's running very good, i did not spot any car duping an server lag.
There are very rare instances where cars get missing, and i can't jet put a finger on when it's happening.
It looks that it's happening on really random moments...

I will keep u updated if i have something usefull...
