### ISSUE TITLE
Car not deleting?

### ISSUE THREAD

**Issue by PeanutSyrup** [hoangducdt/MojiaGarages#78]
Owned cars can't be DVed and if they are /dved they just re-appear instantly after. Seems like they should go to a depot if they are DVed or after server restart instead of staying in middle of street.

**Comment by hoangducdt** [comment]
this is a function not a bug

**Comment by sekem1000** [comment]
how to turn off this function?

**Comment by cadburry6969** [comment]
> ?

![image](https://user-images.githubusercontent.com/72443203/163342516-2482d0d9-04d5-44dd-8582-6e2d5383a9c5.png)
this will be true set it to false

**Comment by cadburry6969** [comment]
> 

![image](https://user-images.githubusercontent.com/72443203/165593628-85883859-c6a5-4712-95ec-bc2849d4c6ee.png)
Comment these
