### ISSUE TITLE
Not detecting all the keys

### ISSUE THREAD

**Issue by Alexfivem** [hoangducdt/MojiaGarages#80]
Issue:  When using qb-vehiclekeys, it detects only the key for one vehicle.

Steps to reproduce:
1) Spawn/take 3 cars out of the garage.
2) Restart the server
3) Log back in to the server. The vehicles will spawn.  Try to open all 3 of the vehicles. Only one can be opened. 

Version used:  Last commit to date

**Comment by Gubner** [comment]
In client.lua, there is a typo. Try changing line 1456:

updateOutSiteVehicleKeys
to
updateOutsiteVehicleKeys

See if that resolves this issue.
