### ISSUE TITLE
Updated qb-phone (fix for qb-phone garages)

### ISSUE THREAD

**Issue by WillFatty** [hoangducdt/MojiaGarages#82]
QBCore updated the phone from
`QBCore.Functions.TriggerCallback('qb-phone:server:GetGarageVehicles',function(vehicles)`
to
`QBCore.Functions.TriggerCallback('qb-garage:server:GetPlayerVehicles', function(vehicles)`

So update the readme so people change it back, and add the following to the qb-phone\server\main.lua

```
QBCore.Functions.CreateCallback('qb-phone:server:GetGarageVehicles', function(source, cb)
    local Player = QBCore.Functions.GetPlayer(source)
    local Vehicles = {}
    local result = MySQL.Sync.fetchAll('SELECT * FROM player_vehicles WHERE citizenid = ?',
        {
			Player.PlayerData.citizenid
		}
	)
    if result[1] ~= nil then
        for k, v in pairs(result) do
            local VehicleData = QBCore.Shared.Vehicles[v.vehicle]
			local modifications = json.decode(v.mods)
            local VehicleGarage = "None"
            if v.garage ~= nil then
                if Garages[v.garage] ~= nil then
                    VehicleGarage = Garages[v.garage]["label"]
                end
            end
            local VehicleState = "In"
            if v.state == 0 then
				if v.depotprice == 0 then
					VehicleGarage = "None"
					VehicleState = "Out"
				else
					VehicleGarage = "Depot"
					VehicleState = "In Depot"
				end
            elseif v.state == 2 then
                VehicleGarage = "Police Depot"
				VehicleState = "Impounded"
            end
            local vehdata = {}
            if VehicleData["brand"] ~= nil then
                vehdata = {
                    fullname = VehicleData["brand"] .. " " .. VehicleData["name"],
                    brand = VehicleData["brand"],
                    model = VehicleData["name"],
                    plate = v.plate,
                    garage = VehicleGarage,
                    state = VehicleState,
                    fuel = modifications.fuelLevel,
                    engine = modifications.engineHealth,
                    body = modifications.bodyHealth
                }
            else
                vehdata = {
                    fullname = VehicleData["name"],
                    brand = VehicleData["name"],
                    model = VehicleData["name"],
                    plate = v.plate,
                    garage = VehicleGarage,
                    state = VehicleState,
                    fuel = modifications.fuelLevel,
                    engine = modifications.engineHealth,
                    body = modifications.bodyHealth
                }
            end
            Vehicles[#Vehicles+1] = vehdata
        end
        cb(Vehicles)
    else
        cb(nil)
    end
end)
```

Otherwise great walkthrough on how to install.

**Comment by sekem1000** [comment]
> QBCore updated the phone from `QBCore.Functions.TriggerCallback('qb-phone:server:GetGarageVehicles',function(vehicles)` to `QBCore.Functions.TriggerCallback('qb-garage:server:GetPlayerVehicles', function(vehicles)`
> 
> So update the readme so people change it back, and add the following to the qb-phone\server\main.lua
> 
> ```
> QBCore.Functions.CreateCallback('qb-phone:server:GetGarageVehicles', function(source, cb)
>     local Player = QBCore.Functions.GetPlayer(source)
>     local Vehicles = {}
>     local result = MySQL.Sync.fetchAll('SELECT * FROM player_vehicles WHERE citizenid = ?',
>         {
> 			Player.PlayerData.citizenid
> 		}
> 	)
>     if result[1] ~= nil then
>         for k, v in pairs(result) do
>             local VehicleData = QBCore.Shared.Vehicles[v.vehicle]
> 			local modifications = json.decode(v.mods)
>             local VehicleGarage = "None"
>             if v.garage ~= nil then
>                 if Garages[v.garage] ~= nil then
>                     VehicleGarage = Garages[v.garage]["label"]
>                 end
>             end
>             local VehicleState = "In"
>             if v.state == 0 then
> 				if v.depotprice == 0 then
> 					VehicleGarage = "None"
> 					VehicleState = "Out"
> 				else
> 					VehicleGarage = "Depot"
> 					VehicleState = "In Depot"
> 				end
>             elseif v.state == 2 then
>                 VehicleGarage = "Police Depot"
> 				VehicleState = "Impounded"
>             end
>             local vehdata = {}
>             if VehicleData["brand"] ~= nil then
>                 vehdata = {
>                     fullname = VehicleData["brand"] .. " " .. VehicleData["name"],
>                     brand = VehicleData["brand"],
>                     model = VehicleData["name"],
>                     plate = v.plate,
>                     garage = VehicleGarage,
>                     state = VehicleState,
>                     fuel = modifications.fuelLevel,
>                     engine = modifications.engineHealth,
>                     body = modifications.bodyHealth
>                 }
>             else
>                 vehdata = {
>                     fullname = VehicleData["name"],
>                     brand = VehicleData["name"],
>                     model = VehicleData["name"],
>                     plate = v.plate,
>                     garage = VehicleGarage,
>                     state = VehicleState,
>                     fuel = modifications.fuelLevel,
>                     engine = modifications.engineHealth,
>                     body = modifications.bodyHealth
>                 }
>             end
>             Vehicles[#Vehicles+1] = vehdata
>         end
>         cb(Vehicles)
>     else
>         cb(nil)
>     end
> end)
> ```
> 
> Otherwise great walkthrough on how to install.

read the readme.md carefully server event and client events are mentioned there replace those to your needings and see if it works or not

**Comment by WillFatty** [comment]
> > QBCore updated the phone from `QBCore.Functions.TriggerCallback('qb-phone:server:GetGarageVehicles',function(vehicles)` to `QBCore.Functions.TriggerCallback('qb-garage:server:GetPlayerVehicles', function(vehicles)`
> > 
> > So update the readme so people change it back, and add the following to the qb-phone\server\main.lua
> > 
> > ```
> > QBCore.Functions.CreateCallback('qb-phone:server:GetGarageVehicles', function(source, cb)
> >     local Player = QBCore.Functions.GetPlayer(source)
> >     local Vehicles = {}
> >     local result = MySQL.Sync.fetchAll('SELECT * FROM player_vehicles WHERE citizenid = ?',
> >         {
> > 			Player.PlayerData.citizenid
> > 		}
> > 	)
> >     if result[1] ~= nil then
> >         for k, v in pairs(result) do
> >             local VehicleData = QBCore.Shared.Vehicles[v.vehicle]
> > 			local modifications = json.decode(v.mods)
> >             local VehicleGarage = "None"
> >             if v.garage ~= nil then
> >                 if Garages[v.garage] ~= nil then
> >                     VehicleGarage = Garages[v.garage]["label"]
> >                 end
> >             end
> >             local VehicleState = "In"
> >             if v.state == 0 then
> > 				if v.depotprice == 0 then
> > 					VehicleGarage = "None"
> > 					VehicleState = "Out"
> > 				else
> > 					VehicleGarage = "Depot"
> > 					VehicleState = "In Depot"
> > 				end
> >             elseif v.state == 2 then
> >                 VehicleGarage = "Police Depot"
> > 				VehicleState = "Impounded"
> >             end
> >             local vehdata = {}
> >             if VehicleData["brand"] ~= nil then
> >                 vehdata = {
> >                     fullname = VehicleData["brand"] .. " " .. VehicleData["name"],
> >                     brand = VehicleData["brand"],
> >                     model = VehicleData["name"],
> >                     plate = v.plate,
> >                     garage = VehicleGarage,
> >                     state = VehicleState,
> >                     fuel = modifications.fuelLevel,
> >                     engine = modifications.engineHealth,
> >                     body = modifications.bodyHealth
> >                 }
> >             else
> >                 vehdata = {
> >                     fullname = VehicleData["name"],
> >                     brand = VehicleData["name"],
> >                     model = VehicleData["name"],
> >                     plate = v.plate,
> >                     garage = VehicleGarage,
> >                     state = VehicleState,
> >                     fuel = modifications.fuelLevel,
> >                     engine = modifications.engineHealth,
> >                     body = modifications.bodyHealth
> >                 }
> >             end
> >             Vehicles[#Vehicles+1] = vehdata
> >         end
> >         cb(Vehicles)
> >     else
> >         cb(nil)
> >     end
> > end)
> > ```
> > 
> > Otherwise great walkthrough on how to install.
> 
> read the readme.md carefully server event and client events are mentioned there replace those to your needings and see if it works or not

They just updated it so this isn't relevant anymore.
