### ISSUE TITLE
modType and modIndex

### ISSUE THREAD

**Issue by Terodiac** [hoangducdt/MojiaGarages#95]
Hi there! 

We have it all set up nicely and made a PD garage.

Now we want to make it so the basic police car spawns with a certain set of modifications, and to our understanding, the "modType" and the "modIndex" should help with that. However, there is 0 documentation or no info on how it needs to be put in. We tried a number of variations with using [this](https://wiki.rage.mp/index.php?title=Vehicle_Mods) as an guide, but with all things we tried it never showed up with one of the mods selected out of the garage.

Anyone has an idea how to properly code this so the car always spawns with a set of mods we chose (bumper, roof etc)?

**Comment by hoangducdt** [comment]
https://docs.fivem.net/natives/?_0x6AF0636DDEDCB6DD

**Comment by Terodiac** [comment]
Hi, this is not really helpful for my case, can you give me an example how to use this? 

Cause you dont specify how you have written it and where to put what number. This data you linked me does not do that as well. 

If i want for example a bumper (that has 3 options for the specific car, i want option 2) and a roof (with 2 options for the specific car, i want option 1) on the setup car, how would i write that in your code?

What would be the way the modType is written?
What would be the way the modIndex is written?

Thanks in advance

**Comment by Terodiac** [comment]
Bump.

**Comment by Terodiac** [comment]
Like anyone else has an idea? Why is there a function in this script that is not explained?

**Comment by hoangducdt** [comment]
How to apply modtype and modindex to vehicles is generally so clear that no further explanation is needed! Determining the modtype and modindex for a particular vehicle depends on what the vehicle has and you have to do it yourself, it's your own problem.
