### ISSUE TITLE
Problemas whit a export

### ISSUE THREAD

**Issue by justBMR** [hoangducdt/MojiaGarages#99]
I People.
Somebody know whats the problem? I follow all steps, and i have that on my F8 console.
MojiaGarages Script error: citizen:/scripting/lua/scheduler.lua:867: No such export CheckHasKey in resource MojiaVehicleKeys

Tanks for the help

**Comment by agung08** [comment]
if you don't use MojiaVehicleKeys open config -> UsingMojiaVehiclekeys = false
